/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    InstaPay: {
      address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "hirer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "worker",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "JobCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
          ],
          name: "JobPaid",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address payable",
              name: "_worker",
              type: "address",
            },
          ],
          name: "createAndFundJob",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "jobCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "jobs",
          outputs: [
            {
              internalType: "address payable",
              name: "hirer",
              type: "address",
            },
            {
              internalType: "address payable",
              name: "worker",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "paid",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_jobId",
              type: "uint256",
            },
          ],
          name: "releasePayment",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 3,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
